[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"