name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Check for outdated packages
        id: outdated
        run: |
          outdated_output=$(npm outdated --json || echo '{}')
          echo "outdated_packages=$outdated_output" >> $GITHUB_OUTPUT

      - name: Update patch and minor versions
        run: |
          npm update --legacy-peer-deps

      - name: Run security audit and fix
        run: |
          npm audit fix --legacy-peer-deps || true

      - name: Check if package-lock.json changed
        id: changes
        run: |
          if git diff --quiet package-lock.json; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: automated dependency updates'
          body: |
            ## Automated Dependency Updates

            This PR contains automated dependency updates:
            - Updated patch and minor versions
            - Applied security fixes

            ### Changes
            - Updated package-lock.json

            ### Testing
            - [ ] CI/CD pipeline passes
            - [ ] Build succeeds
            - [ ] No breaking changes detected

            **Note**: This PR was created automatically. Please review the changes before merging.
          branch: chore/dependency-updates
          delete-branch: true

      - name: Enable auto-merge for dependency updates
        if: steps.changes.outputs.changes == 'true'
        run: |
          echo "Auto-merge can be enabled manually after CI passes"
